CREATE TABLE IF NOT EXISTS trip_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trip_id INT UNSIGNED NOT NULL,
  from_user_id INT UNSIGNED NOT NULL,
  to_user_id INT UNSIGNED NOT NULL,
  amount_cents INT UNSIGNED NOT NULL,
  status ENUM('sent', 'confirmed', 'cancelled') NOT NULL DEFAULT 'sent',
  note VARCHAR(255) NULL,
  marked_sent_by INT UNSIGNED NULL,
  marked_sent_at TIMESTAMP NULL DEFAULT NULL,
  confirmed_by INT UNSIGNED NULL,
  confirmed_at TIMESTAMP NULL DEFAULT NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at TIMESTAMP NULL DEFAULT NULL,
  cancel_reason ENUM('sender_cancelled', 'not_received') NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_trip_payments_trip_status (trip_id, status, id),
  KEY idx_trip_payments_trip_pair_status (trip_id, from_user_id, to_user_id, status),
  KEY idx_trip_payments_from_user (from_user_id),
  KEY idx_trip_payments_to_user (to_user_id),
  CONSTRAINT fk_trip_payments_trip_id FOREIGN KEY (trip_id) REFERENCES trip_trips(id) ON DELETE CASCADE,
  CONSTRAINT fk_trip_payments_from_user FOREIGN KEY (from_user_id) REFERENCES trip_users(id) ON DELETE CASCADE,
  CONSTRAINT fk_trip_payments_to_user FOREIGN KEY (to_user_id) REFERENCES trip_users(id) ON DELETE CASCADE,
  CONSTRAINT fk_trip_payments_marked_sent_by FOREIGN KEY (marked_sent_by) REFERENCES trip_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_trip_payments_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES trip_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_trip_payments_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES trip_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
