CREATE TABLE IF NOT EXISTS trip_random_draw_state (
  id TINYINT UNSIGNED NOT NULL DEFAULT 1,
  members_csv VARCHAR(1024) NOT NULL,
  remaining_csv VARCHAR(1024) NOT NULL,
  cycle_no INT UNSIGNED NOT NULL DEFAULT 1,
  draw_no INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
