<?php
declare(strict_types=1);

define('DB_HOST', env_string('TRIP_DB_HOST', 'localhost'));
define('DB_NAME', env_string('TRIP_DB_NAME', ''));
define('DB_USER', env_string('TRIP_DB_USER', ''));
define('DB_PASS', env_string('TRIP_DB_PASS', ''));
define('APP_DEBUG', env_bool('TRIP_APP_DEBUG', false));
define('TRUST_PROXY_HEADERS', env_bool('TRIP_TRUST_PROXY_HEADERS', false));
define('PUBLIC_BASE_URL', env_string('TRIP_PUBLIC_BASE_URL', ''));
define('API_MAX_JSON_BYTES', env_int('TRIP_API_MAX_JSON_BYTES', 65_536)); // 64 KB
define('DB_TABLE_PREFIX', env_string('TRIP_DB_TABLE_PREFIX', 'trip_'));
define('ADMIN_KEY', env_string('TRIP_ADMIN_KEY', ''));
define('RECEIPTS_REL_DIR', env_string('TRIP_RECEIPTS_REL_DIR', 'uploads/receipts'));
define('RECEIPTS_MAX_BYTES', env_int('TRIP_RECEIPTS_MAX_BYTES', 8_388_608)); // 8 MB
define('AVATARS_REL_DIR', env_string('TRIP_AVATARS_REL_DIR', 'uploads/avatars'));
define('AVATARS_MAX_BYTES', env_int('TRIP_AVATARS_MAX_BYTES', 5_242_880)); // 5 MB
define('TRIP_IMAGES_REL_DIR', env_string('TRIP_IMAGES_REL_DIR', 'uploads/trips'));
define('TRIP_IMAGES_MAX_BYTES', env_int('TRIP_IMAGES_MAX_BYTES', 8_388_608)); // 8 MB
define('FEEDBACK_REL_DIR', env_string('TRIP_FEEDBACK_REL_DIR', 'uploads/feedback'));
define('FEEDBACK_MAX_BYTES', env_int('TRIP_FEEDBACK_MAX_BYTES', 8_388_608)); // 8 MB
define('UPLOAD_IMAGE_WEBP_QUALITY', env_int('TRIP_UPLOAD_IMAGE_WEBP_QUALITY', 84));
define('UPLOAD_IMAGE_THUMB_MAX_SIDE', env_int('TRIP_UPLOAD_IMAGE_THUMB_MAX_SIDE', 420));
define('UPLOAD_IMAGE_THUMB_WEBP_QUALITY', env_int('TRIP_UPLOAD_IMAGE_THUMB_WEBP_QUALITY', 76));
define('CLASS_UPLOAD_REL_PATH', env_string('TRIP_CLASS_UPLOAD_REL_PATH', 'api/lib/verot/class.upload.php'));
define('API_ERROR_LOG_REL_PATH', env_string('TRIP_API_ERROR_LOG_REL_PATH', 'logs/api-error.log'));

define('PUSH_ENABLED', env_bool('TRIP_PUSH_ENABLED', false));
define('PUSH_FCM_SERVER_KEY', env_string('TRIP_PUSH_FCM_SERVER_KEY', ''));
define('PUSH_FCM_PROJECT_ID', env_string('TRIP_PUSH_FCM_PROJECT_ID', ''));
define('PUSH_FCM_SERVICE_ACCOUNT_REL_PATH', env_string('TRIP_PUSH_FCM_SERVICE_ACCOUNT_REL_PATH', ''));
define('PUSH_APNS_ENABLED', env_bool('TRIP_PUSH_APNS_ENABLED', false));
define('PUSH_APNS_TEAM_ID', env_string('TRIP_PUSH_APNS_TEAM_ID', ''));
define('PUSH_APNS_KEY_ID', env_string('TRIP_PUSH_APNS_KEY_ID', ''));
define('PUSH_APNS_BUNDLE_ID', env_string('TRIP_PUSH_APNS_BUNDLE_ID', ''));
define('PUSH_APNS_PRIVATE_KEY_REL_PATH', env_string('TRIP_PUSH_APNS_PRIVATE_KEY_REL_PATH', ''));
define('PUSH_APNS_USE_SANDBOX', env_bool('TRIP_PUSH_APNS_USE_SANDBOX', false));
define('PUSH_TIMEOUT_SEC', env_int('TRIP_PUSH_TIMEOUT_SEC', 8));
define('PUSH_MAX_TOKENS_PER_USER', env_int('TRIP_PUSH_MAX_TOKENS_PER_USER', 5));
define('PUSH_QUEUE_BATCH_LIMIT', env_int('TRIP_PUSH_QUEUE_BATCH_LIMIT', 100));
define(
    'PUSH_CRITICAL_TYPES',
    env_string(
        'TRIP_PUSH_CRITICAL_TYPES',
        'trip_finished,trip_ready_to_settle,settlement_sent,settlement_confirmed,settlement_reminder,settlement_auto_reminder,expense_added,friend_invite_received'
    )
);

define('SETTLEMENT_REMINDER_ENABLED', env_bool('TRIP_SETTLEMENT_REMINDER_ENABLED', false));
define('SETTLEMENT_REMINDER_INTERVAL_MIN', env_int('TRIP_SETTLEMENT_REMINDER_INTERVAL_MIN', 720));
define('SETTLEMENT_REMINDER_MIN_AGE_MIN', env_int('TRIP_SETTLEMENT_REMINDER_MIN_AGE_MIN', 180));
define('SETTLEMENT_REMINDER_BATCH_LIMIT', env_int('TRIP_SETTLEMENT_REMINDER_BATCH_LIMIT', 120));
define('SETTLEMENT_MANUAL_REMINDER_COOLDOWN_MIN', env_int('TRIP_SETTLEMENT_MANUAL_REMINDER_COOLDOWN_MIN', 15));

define('RATE_LIMIT_REGISTER_IP_MAX', env_int('TRIP_RATE_LIMIT_REGISTER_IP_MAX', 40));
define('RATE_LIMIT_REGISTER_TOKEN_MAX', env_int('TRIP_RATE_LIMIT_REGISTER_TOKEN_MAX', 15));
define('RATE_LIMIT_REGISTER_PROOF_IP_MAX', env_int('TRIP_RATE_LIMIT_REGISTER_PROOF_IP_MAX', 120));
define('RATE_LIMIT_REGISTER_PROOF_TOKEN_MAX', env_int('TRIP_RATE_LIMIT_REGISTER_PROOF_TOKEN_MAX', 80));
define('RATE_LIMIT_LOGIN_IP_MAX', env_int('TRIP_RATE_LIMIT_LOGIN_IP_MAX', 60));
define('RATE_LIMIT_LOGIN_EMAIL_MAX', env_int('TRIP_RATE_LIMIT_LOGIN_EMAIL_MAX', 20));
define('RATE_LIMIT_REFRESH_IP_MAX', env_int('TRIP_RATE_LIMIT_REFRESH_IP_MAX', 120));
define('RATE_LIMIT_REFRESH_TOKEN_MAX', env_int('TRIP_RATE_LIMIT_REFRESH_TOKEN_MAX', 80));
define('RATE_LIMIT_UPLOAD_IP_MAX', env_int('TRIP_RATE_LIMIT_UPLOAD_IP_MAX', 80));
define('RATE_LIMIT_UPLOAD_USER_MAX', env_int('TRIP_RATE_LIMIT_UPLOAD_USER_MAX', 40));
define('RATE_LIMIT_SEARCH_IP_MAX', env_int('TRIP_RATE_LIMIT_SEARCH_IP_MAX', 180));
define('RATE_LIMIT_SEARCH_USER_MAX', env_int('TRIP_RATE_LIMIT_SEARCH_USER_MAX', 120));
define('RATE_LIMIT_FRIENDS_INVITE_IP_MAX', env_int('TRIP_RATE_LIMIT_FRIENDS_INVITE_IP_MAX', 80));
define('RATE_LIMIT_FRIENDS_INVITE_USER_MAX', env_int('TRIP_RATE_LIMIT_FRIENDS_INVITE_USER_MAX', 60));
define('RATE_LIMIT_TRIP_WRITE_IP_MAX', env_int('TRIP_RATE_LIMIT_TRIP_WRITE_IP_MAX', 80));
define('RATE_LIMIT_TRIP_WRITE_USER_MAX', env_int('TRIP_RATE_LIMIT_TRIP_WRITE_USER_MAX', 60));
define('RATE_LIMIT_EXPENSE_WRITE_IP_MAX', env_int('TRIP_RATE_LIMIT_EXPENSE_WRITE_IP_MAX', 240));
define('RATE_LIMIT_EXPENSE_WRITE_USER_MAX', env_int('TRIP_RATE_LIMIT_EXPENSE_WRITE_USER_MAX', 180));
define('RATE_LIMIT_FEEDBACK_IP_MAX', env_int('TRIP_RATE_LIMIT_FEEDBACK_IP_MAX', 40));
define('RATE_LIMIT_FEEDBACK_USER_MAX', env_int('TRIP_RATE_LIMIT_FEEDBACK_USER_MAX', 30));
define('RATE_LIMIT_ADMIN_AUTH_IP_MAX', env_int('TRIP_RATE_LIMIT_ADMIN_AUTH_IP_MAX', 60));

define('RATE_LIMIT_REGISTER_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_REGISTER_WINDOW_SEC', 3600));
define('RATE_LIMIT_LOGIN_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_LOGIN_WINDOW_SEC', 3600));
define('RATE_LIMIT_REFRESH_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_REFRESH_WINDOW_SEC', 3600));
define('RATE_LIMIT_UPLOAD_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_UPLOAD_WINDOW_SEC', 600));
define('RATE_LIMIT_SEARCH_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_SEARCH_WINDOW_SEC', 600));
define('RATE_LIMIT_MUTATION_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_MUTATION_WINDOW_SEC', 3600));
define('RATE_LIMIT_ADMIN_WINDOW_SEC', env_int('TRIP_RATE_LIMIT_ADMIN_WINDOW_SEC', 900));

define('REGISTER_PROOF_SECRET', env_string('TRIP_REGISTER_PROOF_SECRET', ''));
define('REGISTER_PROOF_MAX_AGE_SEC', env_int('TRIP_REGISTER_PROOF_MAX_AGE_SEC', 900));
define('AUTH_ACCESS_TOKEN_SECRET', env_string('TRIP_AUTH_ACCESS_TOKEN_SECRET', ''));
define('AUTH_ACCESS_TOKEN_TTL_SEC', env_int('TRIP_AUTH_ACCESS_TOKEN_TTL_SEC', 900));
define('AUTH_REFRESH_TOKEN_TTL_SEC', env_int('TRIP_AUTH_REFRESH_TOKEN_TTL_SEC', 2_592_000));
define('EMAIL_VERIFICATION_REQUIRED', env_bool('TRIP_EMAIL_VERIFICATION_REQUIRED', true));
define('EMAIL_VERIFICATION_TOKEN_TTL_SEC', env_int('TRIP_EMAIL_VERIFICATION_TOKEN_TTL_SEC', 86_400));
define('EMAIL_VERIFICATION_GRACE_DAYS', env_int('TRIP_EMAIL_VERIFICATION_GRACE_DAYS', 7));
define('EMAIL_VERIFICATION_CLEANUP_BATCH_LIMIT', env_int('TRIP_EMAIL_VERIFICATION_CLEANUP_BATCH_LIMIT', 300));
define('EMAIL_CHANGE_TOKEN_TTL_SEC', env_int('TRIP_EMAIL_CHANGE_TOKEN_TTL_SEC', 86_400));
define('ACCOUNT_REACTIVATION_TOKEN_TTL_SEC', env_int('TRIP_ACCOUNT_REACTIVATION_TOKEN_TTL_SEC', 86_400));
define('ACCOUNT_DELETION_TOKEN_TTL_SEC', env_int('TRIP_ACCOUNT_DELETION_TOKEN_TTL_SEC', 3_600));
define('SOCIAL_AUTH_ENABLED', env_bool('TRIP_SOCIAL_AUTH_ENABLED', true));
define('SOCIAL_AUTH_TIMEOUT_SEC', env_int('TRIP_SOCIAL_AUTH_TIMEOUT_SEC', 8));
define('SOCIAL_AUTH_GOOGLE_CLIENT_IDS', env_string('TRIP_SOCIAL_AUTH_GOOGLE_CLIENT_IDS', ''));
define('SOCIAL_AUTH_APPLE_CLIENT_IDS', env_string('TRIP_SOCIAL_AUTH_APPLE_CLIENT_IDS', ''));
define('FX_PROVIDER_BASE_URL', env_string('TRIP_FX_PROVIDER_BASE_URL', 'https://api.frankfurter.app'));
define('FX_TIMEOUT_SEC', env_int('TRIP_FX_TIMEOUT_SEC', 8));

define('RESEND_API_KEY', env_string('TRIP_RESEND_API_KEY', ''));
define('RESEND_FROM_ADDRESS', env_string('TRIP_RESEND_FROM_ADDRESS', 'Splyto <noreply@egm.lv>'));
define('APP_BASE_URL', env_string('TRIP_APP_BASE_URL', 'https://splyto.egm.lv'));

define('UPLOAD_USER_MAX_FILES_PER_DAY', env_int('TRIP_UPLOAD_USER_MAX_FILES_PER_DAY', 60));
define('UPLOAD_USER_MAX_BYTES_PER_DAY', env_int('TRIP_UPLOAD_USER_MAX_BYTES_PER_DAY', 251_658_240)); // 240 MB
define('UPLOAD_TRIP_MAX_FILES_PER_DAY', env_int('TRIP_UPLOAD_TRIP_MAX_FILES_PER_DAY', 300));
define('UPLOAD_TRIP_MAX_BYTES_PER_DAY', env_int('TRIP_UPLOAD_TRIP_MAX_BYTES_PER_DAY', 1_073_741_824)); // 1 GB
